export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
DEFAULT_USER="gaoyan"
#ZSH_THEME="robbyrussell"
#plugins=(git  zsh-syntax-highlighting extract z safe-paste zsh-autosuggestions osx web-search python go)
plugins=(git extract z safe-paste zsh-autosuggestions osx python go)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
export EDITOR='vim'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GOPATH=/usr/local/Cellar/go/vim-go
PATH=/usr/local/go/bin:$PATH

export CLICOLOR=1


if [[ -e ~/.zsh_alias ]];then
    source ~/.zsh_alias
fi
if [[ -e ~/.zsh_function ]];then
    source ~/.zsh_function
fi

unsetopt share_history
setopt inc_append_history
#setopt APPEND_HISTORY
setopt hist_ignore_space
